/** Declaration file generated by dts-gen */

export const serve: any[];

export function generateHTML(swaggerDoc: any, opts?: any, options?: any, customCss?: any, customfavIcon?: any, swaggerUrl?: any, customeSiteTitle?: any): any;

export function serveFiles(swaggerDoc: any, opts?: any): any;

export function serveWithOptions(options: any): void;

export function setup(swaggerDoc: any, opts?: any, options?: any, customCss?: any, customfavIcon?: any, swaggerUrl?: any, customeSiteTitle?: any): any;

export namespace generateHTML {
    const prototype: {
    };

}

export namespace serveFiles {
    const prototype: {
    };

}

export namespace setup {
    const prototype: {
    };

}

